version: '3.4'

networks:
  proxy:
   external:
    name: proxy

configs:
  traefik_toml:
    external:
     name: traefik_toml_prod_v1

services:
  traefik:
    image: traefik:1.5.0-rc5
    ports:
    - target: 80
      protocol: tcp
      published: 80
      mode: ingress
    - target: 443
      protocol: tcp
      published: 443
      mode: ingress
    - target: 8080
      protocol: tcp
      published: 8080
      mode: ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /var/tmp:/etc/traefik/acme/
    networks:
      - proxy
    configs:
    - source: traefik_toml
      target: /etc/traefik/traefik.toml
      uid: '1'
      gid: '1'
      mode: 0700
    deploy:
     replicas: 1
     placement:
      constraints:
      - node.role == manager
      - node.hostname == rombus