version: '3.4'

networks:
  proxy:
   external:
    name: proxy
  consul:
   external:
    name: consul-dev_consul
    
configs:
  traefik_toml:
    external:
     name: traefik_toml_prod_v4

services:
  traefik-init:
    image: traefik:latest
    command:
      - "storeconfig"
      - "--api"
      - "--accesslog=true"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--acme=true"
      - "--acme.acmelogging=true"
      - "--acme.storage=traefik/acme/account"
      - "--acme.entryPoint=https"
      - "--acme.httpchallenge=true"
      - "--acme.httpchallenge.entrypoint=http"
      - "--acme.OnHostRule=true"
      - "--acme.onDemand=false"
      - "--acme.email=seffyroff@gmail.com"
      - "--docker"
      - "--docker.exposedbydefault=false"
      - "--docker.swarmmode"
      - "--docker.domain=h3u.org"
      - "--docker.watch"
      - "--consul"
      - "--consul.endpoint=consul.cluster:8500"
      - "--consul.prefix=traefik"
      - "--consul.watch"
      - "--loglevel=INFO"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/tmp:/etc/traefik/acme/
    networks:
      - proxy
      - consul
    deploy:
     restart_policy:
      condition: on-failure
     replicas: 1
     placement:
      constraints:
      - node.role == manager
      - node.hostname == rombus