version: '3.4'

networks:
  proxy:
   external:
    name: proxy
  backend:
   external:
    name: backend
  consul:
   external:
    name: consul-dev_consul

services:
  traefik:
    image: traefik:latest
    command:
    - "--consul"
    - "--consul.endpoint=consul.cluster:8500"
    - "--consul.prefix=traefik"
    - "--consul.watch"
    - "--acme.storage=traefik/acme/account"
    ports:
    - target: 80
      protocol: tcp
      published: 80
      mode: ingress
    - target: 443
      protocol: tcp
      published: 443
      mode: ingress
    - target: 8080
      protocol: tcp
      published: 8080
      mode: ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy
      - consul
      - backend
    deploy:
     replicas: 1
     placement:
      constraints:
      - node.role == manager
      - node.hostname == rombus