version: '3.4'

networks:
  proxy:
   external:
    name: proxy

services:
  traefik:
    image: traefik
    command:  
    - --web
    - --docker
    - --docker.domain=traefik
    - --docker.swarmmode 
    - --docker.exposedbydefault=false
    - --logLevel=INFO
    - --accesslog
    - --entrypoints='Name:http Address::80 Redirect.EntryPoint:https'
    - --entryPoints='Name:https Address::443 TLS'
    - --defaultentrypoints=http,https
    - --acme
    - --acme.storage=/etc/traefik/acme/acme.json
    - --acme.OnHostRule=true
    - --acme.onDemand=false
    - --acme.entrypoint=https
    - --acme.email=seffyroff@gmail.com
    - --acme.caServer='https://acme-staging.api.letsencrypt.org/directory'
    - --acme.domains='h3u.org'
    - --acme.domains= 'hackops.me'
    ports:
    - target: 80
      protocol: tcp
      published: 80
      mode: ingress
    - target: 443
      protocol: tcp
      published: 443
      mode: ingress
    - target: 8080
      protocol: tcp
      published: 8080
      mode: ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == manager
