version: '3.4'

networks:
   consul:

volumes:
   consul:

services:
  consul-server:
    image: consul
    command: agent -server -bootstrap-expect=3 -client 0.0.0.0 -log-level debug -ui -retry-join "consul.cluster"
    environment:
    - 'CONSUL_LOCAL_CONFIG={ "skip_leave_on_interrupt": true }'
    - CONSUL_BIND_INTERFACE=eth0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - consul:/consul/data
    networks:
       consul:
          aliases:
           - consul.cluster
    ports:
    - target: 8500
      published: 8500
      mode: host
    deploy:
     labels:
      traefik.enabled: "false"
     endpoint_mode: dnsrr
     replicas: 2
     placement:
        preferences:
          - spread: node.labels.arch=x64

  consul-pi:
    image: seffyroff/docker-consul-arm64
    command: agent -server -bootstrap-expect=3 -client 0.0.0.0 -log-level debug -ui -retry-join "consul.cluster"
    environment:
    - 'CONSUL_LOCAL_CONFIG={ "skip_leave_on_interrupt": true }'
    - CONSUL_BIND_INTERFACE=eth0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - consul:/consul/data
    networks:
      consul:
        aliases:
         - consul-server-1
    ports:
    - target: 8500
      published: 8500
      mode: host
    deploy:
     labels:
      traefik.enabled: "false"
     replicas: 1
     placement:
      constraints:
      - node.hostname == mincepi