 --entryPoints='Name:http Address::8000 Redirect.EntryPoint:https' 
 --entryPoints='Name:https Address::4442 TLS:tests/traefik.crt,tests/traefik.key;prod/traefik.crt,prod/traefik.key'
 $ docker service create \
--name portainer \
--publish 9000:9000 \
--replicas=1 \
--constraint 'node.role == manager' \
--mount type=bind,src=//var/run/docker.sock,dst=/var/run/docker.sock \
--mount type=bind,src=//opt/portainer,dst=/data \
--labels traefik.port=9000
portainer/portainer \
-H unix:///var/run/docker.sock
docker service create \
    --name whoami1 \
    --publish mode=host,target=80,published=8002 \
    --network proxy \
    --label traefik.backend=whoami1 \
    --label traefik.docker.network=proxy \
    --label traefik.frontend.rule=Host:whoami.h3u.org \
    --label traefik.port=8002 \
    emilevauge/whoami



accessLogsFile = "/dev/stdout"
defaultEntryPoints = ["https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/run/secrets/cert.pem"
      KeyFile = "/run/secrets/key.pem"
[web]
address = ":8080"
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "localhost"
watch = true
swarmmode = true
exposedbydefault = false